[package]
name = "axis-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
poise = "0.6"
serenity = { version = "0.12", default-features = false, features = [
    "client", "gateway", "rustls_backend", "model", "cache"
] }
dotenv = "0.15"
tracing = "0.1"
tracing-subscriber = "0.3"
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
chrono = "0.4"
anyhow = "1.0"
once_cell = "1.19"
regex = "1.10"

[profile.release]
opt-level = 3
lto = true
strip = true
